version: '3.8'

services:
  streamlit:
    build: 
      context: .
      dockerfile: ./docker/streamlit/Dockerfile
    image: streamlit_local
    container_name: streamlit_app
    restart: always
    ports:
      - 8501:8501
    command: streamlit run app/app.py